#!/bin/bash
# Copyright 2019 The Tranquility Base Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
function print_help {
  echo "Welcome to Tranquility Base! This tool performs the required configuration for Marketplace deployment."
  echo
  echo "You will need gcloud authentication as owner role at the Folder level (or Organisation) where Tranquility Base will be deployed."
  echo "If you need to grant gcloud with these permissions please use 'gcloud auth login' and then run the script again."
  echo
  echo "Usage: $0 <arguments>"
  echo "  -b, --billing-account-id <string> (REQUIRED) Billing account ID tied to all Tranquility Base consumption"
  echo "  -f, --parent-folder-id <id> Parent folder ID where the Tranquility Base folder will be created"
  echo "  -o, --organization-id <id> Organisation ID where the Tranquility Base folder will be created"
  echo "  -l, --labels <map(string)> (OPTIONAL) Comma seperated list of key=value pairs to be attached to shared projects"
  echo "  -nl, --no-labels <flag> (OPTIONAL) Override the labelling requirement."
  echo "  Either parent-folder-id or organization-id is REQUIRED"
  echo "Example:"
  echo "  $ ./tb-config-creator -f 705953663545 -b F9C122-73127B-50AE5B -l cost-code=value,business-unit=value,team=tranquility-base,environment=development"
  echo "  $ ./tb-config-creator -o 123953123545 -b F9C122-73127B-50AE5B -nl"

}

PARENT_FOLDER_ID=""
BILLING_ID=""
ORG_ID=""
NO_LABELS=0

while (( "$#" )); do
  case "$1" in
    -r|--random-id)
      RANDOM_ID=$2
      shift 2
      ;;
    -f|--parent-folder-id)
      PARENT_FOLDER_ID=$2
      shift 2
      ;;
    -o|--organization-id )
      ORG_ID=$2
      shift 2
      ;;
    -b|--billing-account-id)
      BILLING_ID=$2
      shift 2
      ;;
    -p|--folder-prefix)
      FOLDER_PREFIX=$2
      shift 2
      ;;
    -l|--labels)
      LABELS=$2
      shift 2
      ;;
    -nl|--no-labels)
      NO_LABELS=1
      shift 
      ;;
    -h|--help)
      print_help
      exit 0
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    --*=|-*) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # unsupported positional arguments
      echo "Error: Unsupported positional argument $1" >&2
      shift
      ;;
  esac
done

## ARG CHECKING

# we need on or the other
if [[ -z ${BILLING_ID} && -z ${PARENT_FOLDER_ID} ]] || [[ -z ${BILLING_ID} && -z ${ORG_ID} ]]; then
  #echo "ERROR: Invalid arguments."
  echo "Error: Either Organisation or Folder ID needs to be provided with a Billing Account"
  exit 1
fi

if [[ -n ${ORG_ID} && -n ${PARENT_FOLDER_ID} ]]; then
  #echo "ERROR: Invalid arguments."
  echo "Error: Either Organisation or Folder ID needs to be provided, not both"
  exit 1
fi

if [[ -z ${LABELS} && ${NO_LABELS} -eq 0 ]]; then
  echo "Error: Labels must either be provided or overriden with the --no-labels flag."
  exit 1
fi

if [[ ${NO_LABELS} -eq 0 ]]; then
  IFS=',' read -r -a array <<< "${LABELS}"

  for index in "${!array[@]}"
  do
      IFS='=' read -r -a array2 <<< "${array[index]}"
      costcode=$(( costcode + $( echo "${array2[0]}" | grep -c "cost-code") ))
      team=$(( team + $( echo "${array2[0]}" | grep -c "team") ))
  done

  if ! [ $costcode -eq 1 ] || ! [ $team -eq 1 ]; then
        if ! [ $costcode -eq 1 ]; then
          printf "%s\n" "Ensure you have a cost-code label and only one"
          printf "%s\n" "e.g. $ ./tb-config-creator -l cost-code=value,team=tranquility-base"
        fi
        if ! [ $team -eq 1 ]; then
          printf "%s\n" "Ensure you have a team label and only one"
          printf "%s\n" "e.g. $ ./tb-config-creator -l cost-code=value,team=tranquility-base"
        fi
        exit 1
  fi
fi

parent_type=""
parent_id=""

if [[ -n ${PARENT_FOLDER_ID}  ]]; then
  # Check parent folder ID
  tb_folder_id=$(gcloud alpha resource-manager folders describe "${PARENT_FOLDER_ID}" --format='value(name)')
  if [[ -z "${tb_folder_id}" ]]; then
    echo "ERROR: Was not able to find the ${PARENT_FOLDER_ID} folder."
    exit 1
  else
    echo "Found parent folder ${PARENT_FOLDER_ID}."
    parent_type="folder"
    parent_id=$PARENT_FOLDER_ID
  fi
fi

if [[ -n ${ORG_ID}  ]]; then
  # Check organization exists
  org_id=$(gcloud organizations  describe "${ORG_ID}" --format='value(name)')
  if [[ -z "${org_id}" ]]; then
    echo "ERROR: Was not able to find the ${ORG_ID} organization."
    exit 1
  else
    echo "Found parent organization ${ORG_ID}."
    parent_type="organization"
    parent_id=${ORG_ID}
  fi
fi

# Check billing account
tb_billing_id=$(gcloud beta billing accounts describe "${BILLING_ID}")
if [[ -z "${tb_billing_id}" ]]; then
  echo "ERROR: Was not able to find the ${BILLING_ID} billing account."
  exit 1
else
  echo "Found billing account ${BILLING_ID}."
fi


function print_confirmation {

  echo; echo "You are about to create a Project to host the Tranquility Base bootstrap server."
  echo "A random project name will be assigned and informed at the end of this configuration"
  echo "In addition, a \"super\" Service Account will be created and several API's will be activated in that project:"
  echo
  echo "1. Permissions of the Service Account:"
  echo "  - at the project level"
  echo "    - compute.admin"
  echo "    - storage.admin"
  echo "    - source.admin"
  echo "    - logger.logWriter"
  echo "  - at the folder level"
  echo "    - resourcemanager.folderAdmin"
  echo "    - resourcemanager.projectCreator"
  echo "    - resourcemanager.projectDeleter"
  echo "    - compute.networkAdmin"
  echo "    - compute.xpnAdmin"
  echo "  - at the billing account level"
  echo "    - billing.admin"
  echo "2.Activation of the following API's:"
  echo "  - cloudbilling.googleapis.com"
  echo "  - cloudkms.googleapis.com"
  echo "  - cloudresourcemanager.googleapis.com"
  echo "  - compute.googleapis.com"
  echo "  - container.googleapis.com"
  echo "  - containerregistry.googleapis.com"
  echo "  - deploymentmanager.googleapis.com"
  echo "  - logging.googleapis.com"
  echo "  - serviceusage.googleapis.com"
  echo "  - sourcerepo.googleapis.com"
  echo "  - storage-api.googleapis.com"
  echo

  read -p "Press Y to continue or any other key to abort: " -n 1 -r
  echo
  if [[ $REPLY != "Y" ]]
  then
    echo "Aborting..."
    exit 0
  fi
}

# Consider automation
if [[ -z ${RANDOM_ID}  ]]; then
  print_confirmation
  RND="$(tr -dc 'a-z0-9' < /dev/urandom | fold -w 8 | sed '/^[0-9]*$/d' | head -n 1)"
else
  RND=${RANDOM_ID}
fi



# Generate a random alphanumeric
PREFIX="bootstrap-"

PROJECT_ID="${PREFIX}${RND}"
SA_NAME="${PREFIX}sa"
SA_EMAIL="${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"

if [[ -z "${tb_billing_id}" ]]; then
  TBASE_FOLDER_PREFIX=$FOLDER_PREFIX
else
  TBASE_FOLDER_PREFIX="Tranquility Base - "
fi

TBASE_FOLDER_NAME="${TBASE_FOLDER_PREFIX}${RND}"

#Explicit labelling is required here because Terraform has not been applied.
ACTIVE_ACCOUNT="$(gcloud config list account --format "value(core.account)" | cut -d@ -f1)"
echo "Resources will be labelled with the owner: ${ACTIVE_ACCOUNT}"
sed -i "s/created-by:.*/created-by: '${ACTIVE_ACCOUNT}'/" "$(dirname "${BASH_SOURCE[0]}")/../tb-dep-manager/test_config.yaml"
# Create Tbase folder to store bootstrap project, involves parsing the output of the glcoud command to get the folder id
tb_folder_id=$(gcloud resource-manager folders create --display-name="${TBASE_FOLDER_NAME}" --"${parent_type}"="${parent_id}" --format="value(name.basename())")

#Add auditing to at folder level
gcloud resource-manager folders get-iam-policy "${tb_folder_id}" > rootfolderiampolicy.yaml
cat >> rootfolderiampolicy.yaml <<EOF
auditConfigs:
- auditLogConfigs:
  - logType: ADMIN_READ
  service: allServices
EOF
gcloud resource-manager folders set-iam-policy "${tb_folder_id}" rootfolderiampolicy.yaml
rm rootfolderiampolicy.yaml

echo "Creating project..."
gcloud projects create "${PROJECT_ID}" --folder "${tb_folder_id}" --format=none --labels created_by="${ACTIVE_ACCOUNT}","${LABELS}"

echo "Linking project to billing account..."
gcloud alpha billing projects link "${PROJECT_ID}" --billing-account "${BILLING_ID}" --format=none
echo "Linked project to billing account [${BILLING_ID}]."

# Create service account
echo "Creating service account..."
gcloud --project "${PROJECT_ID}" iam service-accounts create "${SA_NAME}" --quiet

#Add permissions at the project level
echo "Adding permissions at the project level... "
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.instanceAdmin.v1 --format=none
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/storage.admin --format=none
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/source.admin --format=none
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/logging.logWriter --format=none
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/logging.configWriter --format=none

# Add permissions at the folder level
echo "Adding permissions at the folder level..."
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/resourcemanager.folderAdmin --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/resourcemanager.projectCreator --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/resourcemanager.projectDeleter --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/billing.projectManager --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.networkAdmin --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.xpnAdmin --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.networkUser --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/cloudkms.admin --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/logging.logWriter --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/logging.configWriter --format=none

# Add permissions at the billing level
echo "Adding permission at the billing account level..."
gcloud beta billing accounts add-iam-policy-binding "${BILLING_ID}" --member="serviceAccount:${SA_EMAIL}" --role="roles/billing.admin"

#Activate essential APIs
echo "Activating essential APIs..."
gcloud --project "${PROJECT_ID}" services enable cloudbilling.googleapis.com
gcloud --project "${PROJECT_ID}" services enable cloudkms.googleapis.com
gcloud --project "${PROJECT_ID}" services enable cloudresourcemanager.googleapis.com
gcloud --project "${PROJECT_ID}" services enable compute.googleapis.com
gcloud --project "${PROJECT_ID}" services enable container.googleapis.com
gcloud --project "${PROJECT_ID}" services enable containerregistry.googleapis.com
gcloud --project "${PROJECT_ID}" services enable deploymentmanager.googleapis.com
gcloud --project "${PROJECT_ID}" services enable logging.googleapis.com
gcloud --project "${PROJECT_ID}" services enable serviceusage.googleapis.com
gcloud --project "${PROJECT_ID}" services enable sourcerepo.googleapis.com
gcloud --project "${PROJECT_ID}" services enable storage-api.googleapis.com
gcloud --project "${PROJECT_ID}" services enable runtimeconfig.googleapis.com

echo "Essential APIs activated."

echo "Checking if the default VPC network was created on compute.googleapis.com activation..."
if [[ -n "$(gcloud --project "${PROJECT_ID}" compute networks list --filter='name=default' --format='value(name)' 2> /dev/null)" ]]; then
  echo "The default VPC network was created. Deleting it as per best practices..."
  gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-icmp --quiet
  gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-rdp --quiet
  gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-ssh --quiet
  gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-internal --quiet
  gcloud compute networks delete projects/"${PROJECT_ID}"/global/networks/default --quiet
  echo "Finished deleting the default VPC network."
else
  echo "The default VPC network was not created."
fi

echo
echo "Configuration completed!"
echo "You can now deploy Tranquility Base from Marketplace in project [${PROJECT_ID}], in the [${TBASE_FOLDER_NAME}] folder"
echo
