#!/bin/bash
# Copyright 2019 The Tranquility Base Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
function print_help {
  echo "Welcome to Tranquility Base! This tool performs the required configuration for Marketplace deployment."
  echo
  echo "You will need gcloud authentication as owner role at the Folder level (or Organisation) where Tranquility Base will be deployed."
  echo "If you need to grant gcloud with these permissions please use 'gcloud auth login' and then run the script again."
  echo
  echo "Usage: $0 <arguments>"
  echo "  -b, --billing-account-id <string> (REQUIRED) Billing account ID tied to all Tranquility Base consumption"
  echo "  -f, --parent-folder-id <id> Parent folder ID where the Tranquility Base folder will be created"
  echo "  -o, --organization-id <id> Organisation ID where the Tranquility Base folder will be created"
  echo "  -a, --admin-name <id> (OPTIONAL) admin name to label to bootstrap project"
  echo "  Either parent-folder-id or organization-id is REQUIRED"
  echo "Example:"
  echo "  $ ./tb-config-creator -f 705953663545 -b F9C122-73127B-50AE5B"
  echo "  $ ./tb-config-creator -o 123953123545 -b F9C122-73127B-50AE5B"

}

PARENT_FOLDER_ID=""
BILLING_ID=""
ORG_ID=""
ADMIN=""

while (( "$#" )); do
  case "$1" in
    -f|--parent-folder-id)
      PARENT_FOLDER_ID=$2
      shift 2
      ;;
    -o|--organization-id )
      ORG_ID=$2
      shift 2
      ;;
    -b|--billing-account-id)
      BILLING_ID=$2
      shift 2
      ;;
    -a|--admin-name)
      ADMIN=$2
      shift 2
      ;;
    -h|--help)
      print_help
      exit 0
      ;;

    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # unsupported positional arguments
      echo "Error: Unsupported positional argument $1" >&2
      shift
      ;;
  esac
done

## ARG CHECKING

# we need on or the other
if [[ -z ${BILLING_ID} && -z ${PARENT_FOLDER_ID} ]] || [[ -z ${BILLING_ID} && -z ${ORG_ID} ]]; then
  #echo "ERROR: Invalid arguments."
  echo "Error: Either Organisation or Folder ID needs to be provided with a Billing Account"
  exit 1
fi

if [[ -n ${ORG_ID} && -n ${PARENT_FOLDER_ID} ]]; then
  #echo "ERROR: Invalid arguments."
  echo "Error: Either Organisation or Folder ID needs to be provided, not both"
  exit 1
fi

parent_type=""
parent_id=""

if [[ -n ${PARENT_FOLDER_ID}  ]]; then
  # Check parent folder ID
  tb_folder_id=$(gcloud alpha resource-manager folders describe "${PARENT_FOLDER_ID}" --format='value(name)')
  if [[ -z "${tb_folder_id}" ]]; then
    echo "ERROR: Was not able to find the ${PARENT_FOLDER_ID} folder."
    exit 1
  else
    echo "Found parent folder ${PARENT_FOLDER_ID}."
    parent_type="folder"
    parent_id=$PARENT_FOLDER_ID
  fi
fi

if [[ -n ${ORG_ID}  ]]; then
  # Check organization exists
  org_id=$(gcloud organizations  describe "${ORG_ID}" --format='value(name)')
  if [[ -z "${org_id}" ]]; then
    echo "ERROR: Was not able to find the ${ORG_ID} organization."
    exit 1
  else
    echo "Found parent organization ${ORG_ID}."
    parent_type="organization"
    parent_id=${ORG_ID}
  fi
fi


# Check billing account
tb_billing_id=$(gcloud beta billing accounts describe "${BILLING_ID}")
if [[ -z "${tb_billing_id}" ]]; then
  echo "ERROR: Was not able to find the ${BILLING_ID} billing account."
  exit 1
else
  echo "Found billing account ${BILLING_ID}."
fi

# Ask for confirmation
echo; echo "You are about to create a Project to host the Tranquility Base bootstrap server."
echo "A random project name will be assigned and informed at the end of this configuration"
echo "In addition, a \"super\" Service Account will be created and several API's will be activated in that project:"
echo
echo "1. Permissions of the Service Account:"
echo "  - at the project level"
echo "    - compute.admin"
echo "    - storage.admin"
echo "    - source.admin"
echo "    - logger.logWriter"
echo "  - at the folder level"
echo "    - resourcemanager.folderAdmin"
echo "    - resourcemanager.projectCreator"
echo "    - resourcemanager.projectDeleter"
echo "    - compute.networkAdmin"
echo "    - compute.xpnAdmin"
echo "  - at the billing account level"
echo "    - billing.admin"
echo "2.Activation of the following API's:"
echo "  - cloudbilling.googleapis.com"
echo "  - cloudkms.googleapis.com"
echo "  - cloudresourcemanager.googleapis.com"
echo "  - compute.googleapis.com"
echo "  - container.googleapis.com"
echo "  - containerregistry.googleapis.com"
echo "  - logging.googleapis.com"
echo "  - serviceusage.googleapis.com"
echo "  - sourcerepo.googleapis.com"
echo "  - storage-api.googleapis.com"
echo

read -p "Press Y to continue or any other key to abort: " -n 1 -r
echo
if [[ $REPLY != "Y" ]]
then
  echo "Aborting..."
  exit 0
fi

# Generate a random alphanumeric
PREFIX="bootstrap-"
RND="$(date | md5sum |  awk '{print substr($0,0,9)}')"
PROJECT_ID="${PREFIX}${RND}"
SA_NAME="${PREFIX}sa"
SA_EMAIL="${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
TBASE_FOLDER_PREFIX="Tranquility Base - "
TBASE_FOLDER_NAME="${TBASE_FOLDER_PREFIX}${RND}"

#Explicit labelling is required here because Terraform has not been appllied.
ACTIVE_ACCOUNT="$(gcloud config list account --format "value(core.account)" | cut -d@ -f1)"
CLIENT="$(gcloud organizations list --format "value(displayName)")"
CLIENT=${CLIENT//./_}
echo "Resources will be labelled with the owner: ${ACTIVE_ACCOUNT} and the client: ${CLIENT}"


# Create Tbase folder to store bootstrap project, involves parsing the output of the glcoud command to get the folder id
folder_id_entry=$(gcloud resource-manager folders create --display-name="${TBASE_FOLDER_NAME}" --"${parent_type}"="${parent_id}" --format="value(name)")
IFS='/' read -ra split_array <<< "$folder_id_entry"
tb_folder_id="$(echo ${split_array[1]} | sed 's/[^0-9]*//g')"


echo "Creating project..."
if [[ -n ${ADMIN}  ]]; then
  gcloud projects create "${PROJECT_ID}" --folder "${tb_folder_id}" --format=none --labels admin=${ADMIN},deployed_by="${ACTIVE_ACCOUNT}",client="${CLIENT}"
else
  gcloud projects create "${PROJECT_ID}" --folder "${tb_folder_id}" --format=none --labels deployed_by="${ACTIVE_ACCOUNT}",client="${CLIENT}"
fi

echo "Linking project to billing account..."
gcloud alpha billing projects link "${PROJECT_ID}" --billing-account "${BILLING_ID}" --format=none
echo "Linked project to billing account [${BILLING_ID}]."

# Create service account
echo "Creating service account..."
gcloud --project "${PROJECT_ID}" iam service-accounts create "${SA_NAME}" --quiet

#Add permissions at the project level
echo "Adding permissions at the project level... "
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.instanceAdmin.v1 --format=none
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/storage.admin --format=none
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/source.admin --format=none
gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/logging.logWriter --format=none

# Add permissions at the folder level
echo "Adding permissions at the folder level..."
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/resourcemanager.folderAdmin --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/resourcemanager.projectCreator --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/resourcemanager.projectDeleter --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/billing.projectManager --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.networkAdmin --format=none
gcloud resource-manager folders add-iam-policy-binding "${tb_folder_id}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.xpnAdmin --format=none

# Add permissions at the billing level
echo "Adding permissions at the billing account level..."
gcloud beta billing accounts get-iam-policy "${BILLING_ID}" > billing.yaml
sa="\ \ - serviceAccount:${SA_EMAIL}"
sed "/billing.admin/i ${sa}" billing.yaml > billing2.yaml
gcloud beta billing accounts set-iam-policy "${BILLING_ID}" billing2.yaml --format=none
rm billing.yaml billing2.yaml

#Activate essential APIs
echo "Activating essential APIs..."
gcloud --project "${PROJECT_ID}" services enable cloudbilling.googleapis.com
gcloud --project "${PROJECT_ID}" services enable cloudkms.googleapis.com
gcloud --project "${PROJECT_ID}" services enable cloudresourcemanager.googleapis.com
gcloud --project "${PROJECT_ID}" services enable compute.googleapis.com
gcloud --project "${PROJECT_ID}" services enable container.googleapis.com
gcloud --project "${PROJECT_ID}" services enable containerregistry.googleapis.com
gcloud --project "${PROJECT_ID}" services enable logging.googleapis.com
gcloud --project "${PROJECT_ID}" services enable serviceusage.googleapis.com
gcloud --project "${PROJECT_ID}" services enable sourcerepo.googleapis.com
gcloud --project "${PROJECT_ID}" services enable storage-api.googleapis.com
gcloud --project "${PROJECT_ID}" services enable runtimeconfig.googleapis.com

echo "Essential APIs activated."

# best practice (needs to be done after compute API is enabled)
echo "Deleting default network..."
gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-icmp --quiet
gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-rdp --quiet
gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-ssh --quiet
gcloud compute firewall-rules delete projects/"${PROJECT_ID}"/global/firewalls/default-allow-internal --quiet
gcloud compute networks delete projects/"${PROJECT_ID}"/global/networks/default --quiet

echo
echo "Configuration completed!"
echo "You can now deploy Tranquility Base from Marketplace in project [${PROJECT_ID}], in the [${TBASE_FOLDER_NAME}] folder"
echo
