# Copyright 2019 The Tranquility Base Authors
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is used for testing only. When the app is deployed through Terraform it is not used.

runtime: python27
api_version: 1
threadsafe: yes
handlers:
  - url: /
    static_files: dist/tb-self-service-portal/index.html
    upload: dist/tb-self-service-portal/index.html
    login: required
  - url: /
    static_dir: dist/tb-self-service-portal/
    login: required
skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^LICENSE
