steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - mod-app-auto-delete
      - --service-account=tb-auto-deleter@appspot.gserviceaccount.com
      - --entry-point=main
      - --runtime=python37
      - --source=tb-gcp-tools/tb-auto-projects-deleter/cloud-function
      - --trigger-topic=run-tb-deleter-script
      - --timeout=540
      - --memory=256
      - --project=tb-auto-deleter
      - --region=europe-west2
    env:
      - EXCLUDE_DELETE_LABEL=dont-delete