{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.gateway.portNumber }}
      name: {{ .Values.gateway.portName }}
      protocol: {{ .Values.gateway.portProtocol }}
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "itop.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - route:
    - destination:
        host: {{ include "itop.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
