imports:
- path: tranquility-base.jinja

resources:
- name: tranquility-base
  type: tranquility-base.jinja
  properties:
    zone: europe-west2-a
    tbBootstrapSA: 'tb-tf-server-builder9@gft-group-public.iam.gserviceaccount.com'
